name: momtx
version: "0.1"
date: 2019-07-04
description: |
    A meataxe that runs on top of the MatObj interface

authors:
    - name: Steve Linton
      url: http://sl4.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Steve Linton
      url: http://sl4.host.cs.st-andrews.ac.uk/

GAP: ">= 4.9"

www: https://stevelinton.github.io/momtx/
readme: README.md
packageinfo: https://stevelinton.github.io/momtx/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/stevelinton/momtx/releases/download/v0.1/momtx-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Lin19</span>]   <b class='BibAuthor'>Linton, S.</b>,
     <i class='BibTitle'>momtx, A meataxe that runs on top of the MatObj interface,
             Version 0.1</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://stevelinton.github.io/momtx/">https://stevelinton.github.io/momtx/</a></span>.
    </p>
    

bibtex: |
    @misc{ momtx0.1,
      author =           {Linton, S.},
      title =            {{momtx}, A meataxe that runs on top of the MatObj interface, {V}ersion 0.1},
      month =            {Jul},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href {https://stevelinton.github.io/momtx/} {\texttt{https://stevelinton.github.io/}\discretionary {}{}{}\texttt{momtx/}}},
      printedkey =       {Lin19}
    }

